# Generated by Django 3.0.7 on 2020-07-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.ImageField(upload_to='')),
                ('image_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=30)),
                ('package_title', models.CharField(max_length=80)),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('age_requirement', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('special_offer', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('tags', models.TextField()),
                ('highlights', models.TextField()),
                ('what_included', models.TextField()),
                ('what_excluded', models.TextField()),
                ('good_to_know', models.TextField()),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_mail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TourType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TransportTypePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.Package')),
                ('transport_type_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_type_id', to='package.TransportType')),
            ],
        ),
        migrations.CreateModel(
            name='TourTypePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='T_package_id', to='package.Package')),
                ('tour_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_type_id', to='package.TourType')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_date', models.DateTimeField(auto_now_add=True)),
                ('review_desc', models.TextField()),
                ('ratings', models.IntegerField(blank=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_package', to='package.Package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='package.Location')),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_id', to='package.Days')),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iti_package_id', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='package.Image')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_id', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_desc', models.TextField()),
                ('guide_name', models.CharField(max_length=30)),
                ('accomodation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodation', to='package.Accomodation')),
                ('meals_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_id', to='package.Meals')),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='package.Event'),
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_name', models.CharField(max_length=50)),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_id', to='package.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_type_id', to='package.ActivityType')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_package', to='package.Package')),
            ],
        ),
    ]
