# Generated by Django 3.0.7 on 2020-10-17 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomodation_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_type', models.CharField(blank=True, choices=[('Instant Booking', 'Instant Booking')], max_length=30, null=True)),
                ('tour_type', models.CharField(blank=True, choices=[('Private', 'Private'), ('Group', 'Group'), ('Private and Group', 'Private and Group')], max_length=50, null=True)),
                ('package_title', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, default='packageImage/blank.png', null=True, upload_to='packageImage')),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('age_requirement', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('special_offer', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_price', models.IntegerField()),
                ('guide_method', models.CharField(blank=True, choices=[('Live Guide/Instructor', 'Live Guide/Instructor'), ('Self guided', 'Self guided')], max_length=30, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('what_included', models.TextField(blank=True, null=True)),
                ('what_excluded', models.TextField(blank=True, null=True)),
                ('good_to_know', models.TextField(blank=True, null=True)),
                ('approve', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('toppings', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Anchovies'), ('b', 'Black olives'), ('p', 'Pepperoni'), ('m', 'Mozzarella')], max_length=10)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_idx', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_mail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_date', models.DateTimeField(auto_now_add=True)),
                ('review_desc', models.TextField()),
                ('ratings', models.FloatField(blank=True)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_package', to='package.Package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locattion_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_package_id', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=35)),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_id', to='package.Days')),
                ('package_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='iti_package_id', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.ImageField(blank=True, default='packageImage/blank.png', null=True, upload_to='packageImage')),
                ('image_title', models.CharField(max_length=40)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_id', to='package.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_desc', models.TextField()),
                ('guide_name', models.CharField(max_length=30)),
                ('accomodation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accomodation', to='package.Accomodation')),
                ('meals_id', models.ManyToManyField(related_name='meals_id', to='package.Meals')),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_id', to='package.Event'),
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_name', models.CharField(max_length=50)),
                ('activity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_id', to='package.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_id', models.ManyToManyField(related_name='activity_type_id', to='package.ActivityType')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_package', to='package.Package')),
            ],
        ),
    ]
