# Generated by Django 3.0.7 on 2020-10-17 16:59

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='accomodation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Hotel'), ('b', 'Guest House'), ('p', 'Resort'), ('m', 'Tent')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Bus'), ('b', 'Plane'), ('p', 'Car'), ('m', 'Jip'), ('f', 'Rickshaw'), ('g', 'Motor cycle'), ('w', 'Ship'), ('v', 'Boat')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Trekking'), ('b', 'Adventure'), ('p', 'Climbing'), ('m', 'Hiking')], max_length=10),
        ),
    ]
