# Generated by Django 3.0.7 on 2020-10-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('Instant Booking', 'Instant Booking')], max_length=30, null=True),
        ),
    ]
