# Generated by Django 3.0.7 on 2020-10-12 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20201010_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='package_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='package.Package'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PackageLocation',
        ),
    ]
