# Generated by Django 3.1.1 on 2020-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_remove_review_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
