# Generated by Django 3.0.7 on 2020-10-19 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20201017_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='city_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
