# Generated by Django 3.0.7 on 2020-07-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20200710_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='activity_type_id',
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_type_id',
            field=models.ManyToManyField(related_name='activity_type_id', to='package.ActivityType'),
        ),
        migrations.AlterField(
            model_name='imagepackage',
            name='image_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_id', to='package.Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tourtypepackage',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='T_package_id', to='package.Package'),
        ),
        migrations.RemoveField(
            model_name='tourtypepackage',
            name='tour_type_id',
        ),
        migrations.AddField(
            model_name='tourtypepackage',
            name='tour_type_id',
            field=models.ManyToManyField(related_name='tour_type_id', to='package.TourType'),
        ),
        migrations.RemoveField(
            model_name='transporttypepackage',
            name='transport_type_id',
        ),
        migrations.AddField(
            model_name='transporttypepackage',
            name='transport_type_id',
            field=models.ManyToManyField(related_name='transport_type_id', to='package.TransportType'),
        ),
    ]
