# Generated by Django 3.1.1 on 2020-12-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_review_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
