# Generated by Django 3.0.7 on 2020-07-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_auto_20200710_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locattion_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_package_id', to='package.Package')),
            ],
        ),
    ]
