# Generated by Django 3.0.7 on 2020-10-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20201013_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporttypepackage',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='transporttypepackage',
            name='transport_type_id',
        ),
        migrations.AlterField(
            model_name='tourtype',
            name='name',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Group', 'Group'), ('Private and Group', 'Private and Group')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TransportType',
        ),
        migrations.DeleteModel(
            name='TransportTypePackage',
        ),
    ]
