# Generated by Django 3.1.1 on 2020-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_auto_20201202_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=30, null=True),
        ),
    ]
