# Generated by Django 3.0.7 on 2020-07-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_maplocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='meals_id',
        ),
        migrations.AddField(
            model_name='event',
            name='meals_id',
            field=models.ManyToManyField(related_name='meals_id', to='package.Meals'),
        ),
    ]
