# Generated by Django 3.0.7 on 2020-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_auto_20201013_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourtype',
            old_name='name',
            new_name='tour_type',
        ),
    ]
