# Generated by Django 3.1.1 on 2020-12-01 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('package', '0006_payment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('special_note', models.CharField(max_length=500)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_agency_id', to='accounts.agency')),
            ],
        ),
    ]
