# Generated by Django 3.0.7 on 2020-10-19 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_review_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='package_id',
        ),
        migrations.AddField(
            model_name='review',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.Package'),
            preserve_default=False,
        ),
    ]
