# Generated by Django 3.0.7 on 2020-10-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_auto_20201013_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
