# Generated by Django 3.0.7 on 2020-10-24 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0009_auto_20201020_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('select_date', models.DateTimeField(auto_now_add=True)),
                ('participants', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('tour_type', models.CharField(max_length=50)),
                ('what_included', models.TextField()),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package', to='package.Package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
