# Generated by Django 3.0.7 on 2020-10-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='what_included',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('card_holder_name', models.CharField(max_length=50)),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='package.Booking')),
            ],
        ),
    ]
