# Generated by Django 3.0.7 on 2020-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_auto_20201026_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('package',)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='select_date',
            field=models.DateTimeField(),
        ),
    ]
