# Generated by Django 3.0.7 on 2020-10-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_auto_20201027_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
