# Generated by Django 3.0.7 on 2020-10-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_auto_20201027_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
