# Generated by Django 3.0.7 on 2020-10-28 00:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('package', '0014_auto_20201027_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tags',
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
