# Generated by Django 3.0.7 on 2020-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_auto_20201028_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='approve',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], max_length=30, null=True),
        ),
    ]
