# Generated by Django 3.0.7 on 2020-10-28 01:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0016_auto_20201028_0659'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='package',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
