# Generated by Django 3.0.7 on 2020-10-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_auto_20201028_0708'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='package',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='approve',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='package',
            name='tags',
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
