# Generated by Django 3.0.7 on 2020-10-28 01:33

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('package', '0018_auto_20201028_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='approve',
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draf', max_length=10),
        ),
        migrations.RemoveField(
            model_name='package',
            name='tags',
        ),
        migrations.AddField(
            model_name='package',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
