# Generated by Django 3.0.7 on 2020-10-28 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0019_auto_20201028_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payable',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
