# Generated by Django 3.0.7 on 2020-06-18 21:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric or contain numbers', regex='^[a-zA-Z0-9.+-]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.CharField(blank=True, choices=[('Bangladeshi', 'Bangladeshi'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese')], max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('passport_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('dietery_requirement', models.CharField(blank=True, max_length=500, null=True)),
                ('medical_condition', models.CharField(blank=True, max_length=500, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('photo', models.FileField(blank=True, default='myImage/blank.png', null=True, upload_to='myImage')),
                ('total_package', models.IntegerField(null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_agency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('editor', 'editor')], max_length=200, null=True)),
                ('photo', models.FileField(blank=True, default='myImage/blank.png', null=True, upload_to='myImage')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
