# Generated by Django 3.0.7 on 2020-06-20 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200619_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.FileField(blank=True, default='myImage/blank.png', null=True, upload_to='myImage'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Passport number must be entered in the format: 'BB 0351657'. ", regex='^(?!^0+$)[a-zA-Z0-9]{3,20}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
