# Generated by Django 3.0.7 on 2020-06-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200623_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
