# Generated by Django 3.0.7 on 2020-10-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_auto_20201013_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='recipe',
            new_name='recipee',
        ),
    ]
