# Generated by Django 3.0.7 on 2020-10-17 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draf', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_type', models.CharField(blank=True, choices=[('Instant Booking', 'Instant Booking')], max_length=30, null=True)),
                ('tour_type', models.CharField(blank=True, choices=[('Private', 'Private'), ('Group', 'Group'), ('Private and Group', 'Private and Group')], max_length=50, null=True)),
                ('package_title', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, default='packageImage/blank.png', null=True, upload_to='packageImage')),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('age_requirement', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('special_offer', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_price', models.IntegerField()),
                ('guide_method', models.CharField(blank=True, choices=[('Live Guide/Instructor', 'Live Guide/Instructor'), ('Self guided', 'Self guided')], max_length=30, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('what_included', models.TextField(blank=True, null=True)),
                ('what_excluded', models.TextField(blank=True, null=True)),
                ('good_to_know', models.TextField(blank=True, null=True)),
                ('approve', models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('toppings', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Trekking'), ('b', 'Adventure'), ('p', 'Climbing'), ('m', 'Hiking')], max_length=10)),
                ('accomodation', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Hotel'), ('b', 'Guest House'), ('p', 'Resort'), ('m', 'Tent')], max_length=10)),
                ('transport', multiselectfield.db.fields.MultiSelectField(choices=[('a', 'Bus'), ('b', 'Plane'), ('p', 'Car'), ('m', 'Jip'), ('f', 'Rickshaw'), ('g', 'Motor cycle'), ('w', 'Ship'), ('v', 'Boat')], max_length=10)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
