# Generated by Django 3.1.1 on 2020-10-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20201030_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='state',
            new_name='age',
        ),
    ]
